#!/bin/bash

K8S_NAMESPACE=default

KEYCLOAK_ENDPOINT=${KEYCLOAK_ENDPOINT:-"http://keycloak.${K8S_NAMESPACE}:8080"}
KEYCLOAK_ADMIN_USER=${KEYCLOAK_ADMIN_USER:-"admin"}
KEYCLOAK_ADMIN_PASSWORD=${KEYCLOAK_ADMIN_PASSWORD:-"admin"}
KEYCLOAK_REALM=${KEYCLOAK_REALM:-"realm01"}
KEYCLOAK_CLIENT_NAME=${KEYCLOAK_CLIENT_NAME:-"client01"}

KEYCLOAK_ORGANIZATION_01=${KEYCLOAK_ORGANIZATION_01:-"org01"}
KEYCLOAK_ORGANIZATION_DOMAIN_01=${KEYCLOAK_ORGANIZATION_DOMAIN_01:-"org01.com"}
USER_EMAIL_01=${USER_EMAIL_01:-"user01@${KEYCLOAK_ORGANIZATION_DOMAIN_01}"}
USER_PASSWORD_01=${USER_PASSWORD_01:-"Passw0rd!"}

KEYCLOAK_ORGANIZATION_02=${KEYCLOAK_ORGANIZATION_02:-"org02"}
KEYCLOAK_ORGANIZATION_DOMAIN_02=${KEYCLOAK_ORGANIZATION_DOMAIN_02:-"org02.com"}
USER_EMAIL_02=${USER_EMAIL_02:-"user02@${KEYCLOAK_ORGANIZATION_DOMAIN_02}"}
USER_PASSWORD_02=${USER_PASSWORD_02:-"Passw0rd!"}
