apiVersion: v1
kind: Pod
metadata:
  name: test-svc
spec:
  containers:
  - name: bash
    image: ubuntu:22.04
    command: ["sleep", "3600"]
  - name: nginx
    image: registry.hub.docker.com/library/nginx:latest
    ports:
    - containerPort: 80
