name: CI for pull requests
on:
  pull_request:
    branches:
      - main

jobs:
  pullrequest-ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Check typo
        run: |
          ./tests/check_typo.sh

      - name: Run install-k3s.sh
        run: |
          ./deployments/k3s/intall-k3s.sh

      - name: Deploy keycloak
        run: |
          ./deployments/keycloak/deploy-keycloak.sh
